import java.sql.*;

import java.awt.CardLayout;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author nyee
 */
public class Swing_NewProfessor extends javax.swing.JPanel {
  public static Professor prof;
    JPanel ProfessorCourses;
    JPanel ProfessorNewCourse;
    JPanel ProfessorRequiredBooks;
    JPanel ProfessorTextbooks;
    JPanel ProfessorNewTextbook;

    /**
     * Creates new form Swing_ProfessorLogin
     */
    public Swing_NewProfessor(JFrame frame, JPanel panelCont, CardLayout cl) {
        initComponents();

        loginBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {

			  String name = nameInput.getText();
			  String email = emailInput.getText();
			  String dept = deptInput.getText();

			  System.out.println("Adding prof " + name + " " + email + " " + " " + dept);


			  prof = new Professor(AppMain.connect, name, email, dept);

			  ProfessorCourses = new Swing_ProfessorCourses(prof, frame, panelCont, cl);
			  ProfessorNewCourse = new Swing_ProfessorNewCourse(prof, frame, panelCont, cl);
			  ProfessorRequiredBooks = new Swing_ProfessorRequiredBooks(prof, frame,
																		panelCont, cl);
			  ProfessorTextbooks = new Swing_ProfessorTextbooks(prof, frame, panelCont,
																cl);
			  ProfessorNewTextbook = new Swing_ProfessorNewTextbook(prof, frame, panelCont,
																	cl);

			  panelCont.add(ProfessorCourses, "ProfessorCourses");
			  panelCont.add(ProfessorRequiredBooks, "ProfessorRequiredBooks");
			  panelCont.add(ProfessorNewCourse, "ProfessorNewCourse");
			  panelCont.add(ProfessorTextbooks, "ProfessorTextbooks");
			  panelCont.add(ProfessorNewTextbook, "ProfessorNewTextbook");

			  cl.show(panelCont, "ProfessorCourses");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profNamelbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        deptLbl = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        emailInput = new javax.swing.JTextField();
        deptInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 0));
        setPreferredSize(new java.awt.Dimension(600, 500));

        profNamelbl.setFont(new java.awt.Font("AppleGothic", 1, 13)); // NOI18N
        profNamelbl.setForeground(new java.awt.Color(255, 255, 255));
        profNamelbl.setText("Name:");

        emailLbl.setFont(new java.awt.Font("AppleGothic", 1, 13)); // NOI18N
        emailLbl.setForeground(new java.awt.Color(255, 255, 255));
        emailLbl.setText("Email:");

        deptLbl.setFont(new java.awt.Font("AppleGothic", 1, 13)); // NOI18N
        deptLbl.setForeground(new java.awt.Color(255, 255, 255));
        deptLbl.setText("Department");

        jLabel1.setFont(new java.awt.Font("Savoye LET", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Professor Information");

        loginBtn.setText("Create");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mustang.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deptLbl)
                    .addComponent(profNamelbl, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLbl, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nameInput)
                        .addComponent(emailInput)
                        .addComponent(deptInput, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(profNamelbl)
                            .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLbl)
                            .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deptLbl)
                            .addComponent(deptInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(loginBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField deptInput;
    private javax.swing.JLabel deptLbl;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel profNamelbl;
    // End of variables declaration//GEN-END:variables
}
