import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author danielpappnew
 */
public class Swing_VendorLogin extends javax.swing.JPanel {

	/**
	 * Creates new form Swing_VendorLogin
	 */
	public Swing_VendorLogin(JFrame frame, JPanel panelCont, CardLayout cl) {
		initComponents();
		newVendorButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent arg0) {
				cl.show(panelCont, "NewVendor");
			}
		});

		loginButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent arg0) {

				String vendorID = jTextField1.getText();
				int idInt = Integer.parseInt(vendorID);

				if (Vendor.IDExists(AppMain.connect, idInt)) {
					Vendor v = new Vendor(AppMain.connect, idInt);

				JPanel VendorTextbooks = new Swing_VendorTextbooks(v, frame, panelCont, cl);
				JPanel VendorNewTextbook = new Swing_VendorNewTextbook(v, frame, panelCont, cl);
				JPanel VendorArchiveTextbooks = new Swing_VendorArchiveTextbooks(v, frame, panelCont, cl);

				panelCont.add(VendorTextbooks, "VendorTextbooks"); //10
				panelCont.add(VendorNewTextbook, "VendorNewTextbook"); //11
				panelCont.add(VendorArchiveTextbooks, "VendorArchiveTextbooks"); //12
				cl.show(panelCont, "VendorTextbooks");

				} else {
					JOptionPane.showMessageDialog(frame, "Your ID is incorrect");
				}

			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		loginButton = new javax.swing.JButton();
		newVendorButton = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();

		setPreferredSize(new java.awt.Dimension(600, 500));

		loginButton.setText("Login");

		newVendorButton.setText("Create New Vendor");

		jLabel1.setText("Enter Vendor ID");

		jLabel2.setText("Vendor Login");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(layout.createSequentialGroup()
						.addGap(71, 71, 71)
						.addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
					.addGroup(layout.createSequentialGroup()
						.addGap(114, 114, 114)
						.addComponent(newVendorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
					.addGroup(layout.createSequentialGroup()
						.addGap(160, 160, 160)
						.addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
					.addGroup(layout.createSequentialGroup()
						.addGap(173, 173, 173)
						.addComponent(jLabel2)))
				.addContainerGap(21, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
				.addContainerGap()
				.addComponent(jLabel2)
				.addGap(43, 43, 43)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(jLabel1)
					.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(33, 33, 33)
				.addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18)
				.addComponent(newVendorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addContainerGap(19, Short.MAX_VALUE))
		);
	}// </editor-fold>//GEN-END:initComponents


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JButton loginButton;
	private javax.swing.JButton newVendorButton;
	// End of variables declaration//GEN-END:variables
}
